from .R1 import R1
from .R2 import R2
from .R3 import R3
from .R4 import R4
from .R5 import R5
from .R6 import R6
from .R7 import R7
from .R8 import R8
from .R9 import R9
from .R10 import R10
from .R11 import R11
from .R12 import R12
from .BirthdayParadox import BirthdayParadox
from .WordCounter import WordCounter
